// NOTE: You must run gather_comtrade_data.mjs before running this script.
// This script takes the country-by-country comtrade data generated by the
// gather script, calculates percentage of that country's imports coming from
// Ukraine, and joins all of this data into a single 00_all_data_ukraine.csv file.

import fs from "fs";
import path from "path";
import * as d3 from "d3";

// fix to make d3.csv work in my env
import fetch from "node-fetch";
global.fetch = fetch;

// read a csv file and parse it into json
const processCsvFile = async (path) => {
  try {
    const contents = fs.readFileSync(path, "utf8");
    if (contents) {
      return d3.csvParse(contents);
    } else {
      return null;
    }
  } catch (e) {
    console.log(`No file found for ${path}`);
    return null;
  }
}

// prefixes a filename with the pwd
const comtradeDataPath = file => path.join(process.cwd(), "public/data/comtrade_imports", file)

// get a list of available country comtrade data files
const fileList = fs.readdirSync(comtradeDataPath(''));

// main
fileList.forEach(async (file) => {
  const countryCsv = await processCsvFile(comtradeDataPath(file))
  if (!countryCsv) {
    return;
  }
  const [countryNumber, countryName] = file.split("_");
  console.log(countryNumber, countryName)
})


